# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MqttClient_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MqttClient_iOS

  pod 'CocoaMQTT'  

  target 'MqttClient_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MqttClient_iOSUITests' do
    # Pods for testing
  end

end

